"""Seed data for the first hackathon demo path."""

from __future__ import annotations

BUYER_PROFILE = {
    "name": "Jignesh",
    "experience": "first-time auction buyer",
    "available_cash": 40_000,
    "monthly_income": 9_000,
    "monthly_expenses": 5_200,
    "current_housing_payment": 2_200,
    "risk_profile": "calculated risk, avoid title/legal traps",
    "investment_goal": "long-term rental",
    "financing_type": "hard money or DSCR loan",
    "target_cash_on_cash_return": 0.10,
    "minimum_emergency_reserve": 2_500,
}

PROPERTIES = {
    "6013-fender-court": {
        "address": "6013 Fender Court",
        "city": "Orlando",
        "county": "Orange County",
        "state": "FL",
        "auction_type": "Treasury / CWS-style auction",
        "auction_url": "https://www.treasury.gov/auctions/treasury/rp/6013fender.shtml",
        "current_bid": 170_000,
        "estimated_after_repair_value": 245_000,
        "estimated_market_rent": 2_200,
        "airbnb_monthly_revenue": 3_000,
        "estimated_repairs": 5_000,
        "repair_condition": "unknown interior condition; placeholder assumes light-to-medium repairs",
        "required_deposit": 25_000,
        "closing_deadline_days": 45,
        "minimum_bid": 170_000,
        "auction_date": "April 30, 2026, 11:00am - 1:00pm ET",
        "inspection_dates": "April 18 and 25, 2026, 11:00am - 2:00pm",
        "parcel_number": "36-24-28-7195-00-180",
        "living_area_sqft": 3_157,
        "site_area_sqft": 11_635,
        "year_built": 2015,
        "bedrooms": 5,
        "bathrooms": 3,
        "zoning": "PUD/Planned Unit Development",
        "auction_terms": {
            "as_is": True,
            "financing_contingency": False,
            "default_penalty": "Deposit may be forfeited if buyer fails to close.",
            "buyer_responsibilities": [
                "Verify title, taxes, occupancy, and code issues before bidding.",
                "Close within auction deadline without financing contingency.",
            ],
        },
        "annual_property_taxes": 6_416,
        "annual_insurance_estimate": 3_600,
        "monthly_hoa": 126,
        "hoa_notes": "HOA dues listed as $377.98 per quarter; buyer transfer fee $150 and capital contribution $1,144.52.",
        "property_management_rate": 0.08,
        "vacancy_rate": 0.07,
        "closing_cost_rate": 0.035,
        "down_payment_rate": 0.25,
        "hard_money_interest_rate": 0.12,
        "loan_term_years": 30,
        "official_research": [
            {
                "source": "Treasury Auction Page",
                "status": "verified",
                "risk_level": "medium",
                "finding": "Official Treasury page lists sale number 26-66-125, $170,000 starting bid, $25,000 deposit, April 30, 2026 online auction, parcel 36-24-28-7195-00-180, 2024 county taxes of about $6,416, and as-is terms.",
                "why_it_matters": "Confirms the property is real and the official auction conditions.",
                "url": "https://www.treasury.gov/auctions/treasury/rp/6013fender.shtml",
            },
            {
                "source": "Treasury Terms of Sale",
                "status": "risk_found",
                "risk_level": "high",
                "finding": "Fast close and as-is terms; financing contingencies are typically not available.",
                "why_it_matters": "A first-time buyer can lose the deposit if financing or title review fails late.",
                "url": "https://home.treasury.gov/services/treasury-auctions",
            },
            {
                "source": "CWS Marketing Auction Listing",
                "status": "needs_review",
                "risk_level": "medium",
                "finding": "Registration, deposit delivery, contract package, and broker notes still need review.",
                "why_it_matters": "CWS usually controls the practical bidding and closing process.",
                "url": "https://cwsmarketing.com/",
            },
            {
                "source": "Orange County Property Appraiser",
                "status": "needs_review",
                "risk_level": "medium",
                "finding": "Confirm parcel id, legal description, square footage, year built, and assessed value.",
                "why_it_matters": "Public facts need to match the auction listing before valuing the deal.",
                "url": "https://ocpaweb.ocpafl.org/",
            },
            {
                "source": "Orange County Tax Collector",
                "status": "risk_found",
                "risk_level": "medium",
                "finding": "Tax balance and tax certificates require verification before bidding.",
                "why_it_matters": "Unpaid taxes can change the real acquisition cost.",
                "url": "https://www.octaxcol.com/",
            },
            {
                "source": "Orange County Comptroller Official Records",
                "status": "needs_review",
                "risk_level": "high",
                "finding": "Deeds, mortgages, releases, liens, judgments, lis pendens, and HOA liens must be searched.",
                "why_it_matters": "This is the highest-risk title diligence source for this buyer profile.",
                "url": "https://or.occompt.com/recorder/eagleweb/docSearch.jsp",
            },
            {
                "source": "Orange County Clerk of Courts",
                "status": "needs_review",
                "risk_level": "high",
                "finding": "Foreclosure, civil litigation, judgments, eviction, probate, and owner litigation need review.",
                "why_it_matters": "Court cases can reveal legal risk that is not visible in a listing.",
                "url": "https://myeclerk.myorangeclerk.com/",
            },
            {
                "source": "City of Orlando Code Enforcement",
                "status": "needs_review",
                "risk_level": "medium",
                "finding": "Check open violations, fines, unsafe structure cases, and compliance deadlines.",
                "why_it_matters": "Code fines and unsafe structure findings can create surprise costs.",
                "url": "https://www.orlando.gov/Building-Development/Code-Enforcement",
            },
            {
                "source": "Orange County Code Violation Search",
                "status": "not_checked",
                "risk_level": "medium",
                "finding": "County-level violations and municipal liens have not been checked.",
                "why_it_matters": "City and county systems may show different violations.",
                "url": "https://www.orangecountyfl.net/",
            },
            {
                "source": "U.S. District Court / PACER",
                "status": "not_checked",
                "risk_level": "high",
                "finding": "Federal forfeiture case, sale order, and claims by other parties have not been reviewed.",
                "why_it_matters": "Treasury auctions may depend on federal forfeiture authority and sale terms.",
                "url": "https://pacer.uscourts.gov/",
            },
        ],
    }
}
